pipeline:
  test:
    image: node:${NODE_VERSION}
    commands:
      - npm install --silent
      - npm test
    environment:
      - NODE_ENV=test

  build:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    repo: evert0n/drone-backend-node
    tags:
      - latest
      - ${DRONE_COMMIT_BRANCH}

  notify:
    image: plugins/slack
    secrets: [slack_webhook]
    channel: zenbot
    when:
      status: [ success, failure ]

