pipeline:

  test:
    image: node:8-alpine
    commands:
      - npm install --silent
      - npm test
    environment:
      - NODE_ENV=test

  build:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    registry: registry.appsrv.com
    repo: registry.appsrv.com/tests/drone-backend-node
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - latest    

  # notify:
  #   image: plugins/slack
  #   secrets: [slack_webhook]
  #   webhook: "${SLACK_WEBHOOK}"
  #   channel: zenbot
  #   when:
  #     status: [ success, failure ]

