pipeline:
  test:
    image: node:${NODE_VERSION}
    commands:
      - npm install --silent
      - npm test
    environment:
      - NODE_ENV=test
  slack:
    secrets: [zenbot_webhook_url]
    commands:
      - 'echo "${ZENBOT_WEBHOOK_URL}"'
    image: plugins/slack
    webhook: ${ZENBOT_WEBHOOK_URL}
    channel: zenbot
    when:
      status: [ success, failure ]

matrix:
  NODE_VERSION:
    - 6-alpine
    - 8-alpine
    - 9-alpine
    - alpine
    - latest
