pipeline:
  test:
    image: node:${NODE_VERSION}
    commands:
      - npm install --silent
      - npm test
    environment:
      - NODE_ENV=test
  slack:
    image: plugins/slack
    commands:
      - 'echo "${ZENBOT_WEBHOOK_URL}"'
    #webhook: ${ZENBOT_WEBHOOK_URL}
    #channel: zenbot
    #when:
    #  status: [ success, failure ]

matrix:
  NODE_VERSION:
    - 6-alpine
    - 8-alpine
    - 9-alpine
    - alpine
    - latest
