pipeline:
  test:
    image: node:${NODE_VERSION}
    commands:
      - npm install --silent
      - npm test
    environment:
      - NODE_ENV=test
      
matrix:
  NODE_VERSION:
    - 6-alpine
    - 8-alpine
    - 9-alpine
    - alpine
    - latest